apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: spring-blog
spec:
  podSelector:
    matchLabels: {app: spring-blog}
  policyTypes: [Ingress, Egress]
  ingress:
  - ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - namespaceSelector: {}
